name = "Personal"
license = "MIT"
licenselink = "https://github.com/artenes/hugo-theme-personal/blob/master/LICENSE.md"
description = "A Hugo theme for personal resume with blog and portfolio"
homepage = "http://artenes.github.io/hugo-theme-personal"
tags = ["personal", "resume", "cv", "vcard", "portfolio", "blog"]
features = ["blog", "portfolio", "experience", "education"]
min_version = 0.17

[author]
  name = "Artenes Nogueira"
  homepage = "artenes.github.io"

# If porting an existing theme
[original]
  name = "FREEHTML5.co"
  homepage = "https://freehtml5.co/"
  repo = ""